language: java
sudo: false
install: mvn ${SPARK} ${JAVA} ${SCALA} -Dmaven.javadoc.skip=true -DskipTests=true -B -V -Dgpg.skip=true install
script: mvn ${SPARK} ${JAVA} ${SCALA} -Dmaven.javadoc.skip=true -q -B -Dgpg.skip=true verify
env:
  global:
    - MAVEN_OPTS=-Xmx2g
matrix:
  include:
    # Covers Java 8, Oracle JDK, and Spark 1.4.x
    - jdk: oraclejdk8
      env: SPARK=-Dspark.version=1.4.1 JAVA=-Djava.version=1.8
    # Covers Scala 2.11
    - jdk: oraclejdk8
      env: SCALA=-Pscala-2.11 SPARK=-Dspark.version=1.4.1
cache:
  directories:
    - $HOME/.m2
